name = "realitea-canvas-signaling"
main = "cloudflare/signaling.ts"
compatibility_date = "2025-01-29"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "SignalingRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]

[vars]
NEXT_PUBLIC_COLLAB_TRANSPORT = "webrtc"
NEXT_PUBLIC_WEBRTC_SIGNALING_URLS = "wss://realitea-canvas-signaling.yuriimashchuk.workers.dev/signaling"
NEXT_PUBLIC_WEBRTC_ROOM_KEY = ""

# Optional: Configure timeouts (defaults are suitable for free tier MVP)
# Uncomment and adjust for paid tier with stricter limits:
# STALE_TIMEOUT_MS = "600000"        # 10 minutes (default)
# HEARTBEAT_INTERVAL_MS = "30000"    # 30 seconds (default)
# MAX_MESSAGES_PER_SEC = "120"       # 120 messages/sec (default)

[observability]
enabled = true
