name = "realitea-canvas-signaling"
main = "cloudflare/signaling.ts"
compatibility_date = "2025-01-29"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "SignalingRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["SignalingRoom"]

[vars]
NEXT_PUBLIC_COLLAB_TRANSPORT = "webrtc"
NEXT_PUBLIC_WEBRTC_SIGNALING_URLS = "wss://<your-workers-subdomain>.workers.dev/signaling"
NEXT_PUBLIC_WEBRTC_ROOM_KEY = ""

[observability]
enabled = true
