name = "realitea-canvas-signaling"
main = "cloudflare/signaling.ts"
compatibility_date = "2025-01-29"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "SignalingRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]

# Environment-specific variables are now configured via the Cloudflare dashboard.
# NEXT_PUBLIC_WEBRTC_SIGNALING_URLS is no longer stored in git; see `.env.example` for reference.

[observability]
enabled = true
